export interface City {
  name: string;
  country: string;
  state?: string;
}

// Fallback cities for major countries
export const CITIES_BY_COUNTRY: Record<string, City[]> = {
  "United States": [
    { name: "New York", country: "United States" },
    { name: "Los Angeles", country: "United States" },
    { name: "Chicago", country: "United States" },
    { name: "Houston", country: "United States" },
    { name: "Phoenix", country: "United States" },
    { name: "Philadelphia", country: "United States" },
    { name: "San Antonio", country: "United States" },
    { name: "San Diego", country: "United States" },
    { name: "Dallas", country: "United States" },
    { name: "San Jose", country: "United States" },
  ],
  "United Kingdom": [
    { name: "London", country: "United Kingdom" },
    { name: "Birmingham", country: "United Kingdom" },
    { name: "Manchester", country: "United Kingdom" },
    { name: "Glasgow", country: "United Kingdom" },
    { name: "Liverpool", country: "United Kingdom" },
    { name: "Leeds", country: "United Kingdom" },
    { name: "Sheffield", country: "United Kingdom" },
    { name: "Edinburgh", country: "United Kingdom" },
    { name: "Bristol", country: "United Kingdom" },
    { name: "Newcastle", country: "United Kingdom" },
  ],
  Nigeria: [
    { name: "Lagos", country: "Nigeria" },
    { name: "Abuja", country: "Nigeria" },
    { name: "Kano", country: "Nigeria" },
    { name: "Ibadan", country: "Nigeria" },
    { name: "Port Harcourt", country: "Nigeria" },
    { name: "Benin City", country: "Nigeria" },
    { name: "Kaduna", country: "Nigeria" },
    { name: "Jos", country: "Nigeria" },
    { name: "Ilorin", country: "Nigeria" },
    { name: "Aba", country: "Nigeria" },
  ],
  Canada: [
    { name: "Toronto", country: "Canada" },
    { name: "Montreal", country: "Canada" },
    { name: "Vancouver", country: "Canada" },
    { name: "Calgary", country: "Canada" },
    { name: "Edmonton", country: "Canada" },
    { name: "Ottawa", country: "Canada" },
    { name: "Winnipeg", country: "Canada" },
    { name: "Quebec City", country: "Canada" },
    { name: "Hamilton", country: "Canada" },
    { name: "Kitchener", country: "Canada" },
  ],
  Germany: [
    { name: "Berlin", country: "Germany" },
    { name: "Hamburg", country: "Germany" },
    { name: "Munich", country: "Germany" },
    { name: "Cologne", country: "Germany" },
    { name: "Frankfurt", country: "Germany" },
    { name: "Stuttgart", country: "Germany" },
    { name: "Düsseldorf", country: "Germany" },
    { name: "Dortmund", country: "Germany" },
    { name: "Essen", country: "Germany" },
    { name: "Leipzig", country: "Germany" },
  ],
  France: [
    { name: "Paris", country: "France" },
    { name: "Marseille", country: "France" },
    { name: "Lyon", country: "France" },
    { name: "Toulouse", country: "France" },
    { name: "Nice", country: "France" },
    { name: "Nantes", country: "France" },
    { name: "Strasbourg", country: "France" },
    { name: "Montpellier", country: "France" },
    { name: "Bordeaux", country: "France" },
    { name: "Lille", country: "France" },
  ],
  Australia: [
    { name: "Sydney", country: "Australia" },
    { name: "Melbourne", country: "Australia" },
    { name: "Brisbane", country: "Australia" },
    { name: "Perth", country: "Australia" },
    { name: "Adelaide", country: "Australia" },
    { name: "Gold Coast", country: "Australia" },
    { name: "Newcastle", country: "Australia" },
    { name: "Canberra", country: "Australia" },
    { name: "Wollongong", country: "Australia" },
    { name: "Hobart", country: "Australia" },
  ],
  India: [
    { name: "Mumbai", country: "India" },
    { name: "Delhi", country: "India" },
    { name: "Bangalore", country: "India" },
    { name: "Hyderabad", country: "India" },
    { name: "Ahmedabad", country: "India" },
    { name: "Chennai", country: "India" },
    { name: "Kolkata", country: "India" },
    { name: "Surat", country: "India" },
    { name: "Pune", country: "India" },
    { name: "Jaipur", country: "India" },
  ],
  Brazil: [
    { name: "São Paulo", country: "Brazil" },
    { name: "Rio de Janeiro", country: "Brazil" },
    { name: "Brasília", country: "Brazil" },
    { name: "Salvador", country: "Brazil" },
    { name: "Fortaleza", country: "Brazil" },
    { name: "Belo Horizonte", country: "Brazil" },
    { name: "Manaus", country: "Brazil" },
    { name: "Curitiba", country: "Brazil" },
    { name: "Recife", country: "Brazil" },
    { name: "Porto Alegre", country: "Brazil" },
  ],
  Japan: [
    { name: "Tokyo", country: "Japan" },
    { name: "Yokohama", country: "Japan" },
    { name: "Osaka", country: "Japan" },
    { name: "Nagoya", country: "Japan" },
    { name: "Sapporo", country: "Japan" },
    { name: "Fukuoka", country: "Japan" },
    { name: "Kobe", country: "Japan" },
    { name: "Kyoto", country: "Japan" },
    { name: "Kawasaki", country: "Japan" },
    { name: "Saitama", country: "Japan" },
  ],
  "South Africa": [
    { name: "Johannesburg", country: "South Africa" },
    { name: "Cape Town", country: "South Africa" },
    { name: "Durban", country: "South Africa" },
    { name: "Pretoria", country: "South Africa" },
    { name: "Port Elizabeth", country: "South Africa" },
    { name: "Bloemfontein", country: "South Africa" },
    { name: "East London", country: "South Africa" },
    { name: "Pietermaritzburg", country: "South Africa" },
    { name: "Nelspruit", country: "South Africa" },
    { name: "Kimberley", country: "South Africa" },
  ],
  Kenya: [
    { name: "Nairobi", country: "Kenya" },
    { name: "Mombasa", country: "Kenya" },
    { name: "Kisumu", country: "Kenya" },
    { name: "Nakuru", country: "Kenya" },
    { name: "Eldoret", country: "Kenya" },
    { name: "Thika", country: "Kenya" },
    { name: "Malindi", country: "Kenya" },
    { name: "Kitale", country: "Kenya" },
    { name: "Garissa", country: "Kenya" },
    { name: "Kakamega", country: "Kenya" },
  ],
  Ghana: [
    { name: "Accra", country: "Ghana" },
    { name: "Kumasi", country: "Ghana" },
    { name: "Tamale", country: "Ghana" },
    { name: "Sekondi-Takoradi", country: "Ghana" },
    { name: "Sunyani", country: "Ghana" },
    { name: "Cape Coast", country: "Ghana" },
    { name: "Koforidua", country: "Ghana" },
    { name: "Ho", country: "Ghana" },
    { name: "Techiman", country: "Ghana" },
    { name: "Bolgatanga", country: "Ghana" },
  ],
  "United Arab Emirates": [
    { name: "Dubai", country: "United Arab Emirates" },
    { name: "Abu Dhabi", country: "United Arab Emirates" },
    { name: "Sharjah", country: "United Arab Emirates" },
    { name: "Ajman", country: "United Arab Emirates" },
    { name: "Ras Al Khaimah", country: "United Arab Emirates" },
    { name: "Fujairah", country: "United Arab Emirates" },
    { name: "Umm Al Quwain", country: "United Arab Emirates" },
  ],
  Singapore: [{ name: "Singapore", country: "Singapore" }],
  Netherlands: [
    { name: "Amsterdam", country: "Netherlands" },
    { name: "Rotterdam", country: "Netherlands" },
    { name: "The Hague", country: "Netherlands" },
    { name: "Utrecht", country: "Netherlands" },
    { name: "Eindhoven", country: "Netherlands" },
    { name: "Tilburg", country: "Netherlands" },
    { name: "Groningen", country: "Netherlands" },
    { name: "Almere", country: "Netherlands" },
    { name: "Breda", country: "Netherlands" },
    { name: "Nijmegen", country: "Netherlands" },
  ],
  China: [
    { name: "Beijing", country: "China" },
    { name: "Shanghai", country: "China" },
    { name: "Guangzhou", country: "China" },
    { name: "Shenzhen", country: "China" },
    { name: "Tianjin", country: "China" },
    { name: "Wuhan", country: "China" },
    { name: "Chengdu", country: "China" },
    { name: "Nanjing", country: "China" },
    { name: "Hangzhou", country: "China" },
    { name: "Xi'an", country: "China" },
  ],
  Italy: [
    { name: "Rome", country: "Italy" },
    { name: "Milan", country: "Italy" },
    { name: "Naples", country: "Italy" },
    { name: "Turin", country: "Italy" },
    { name: "Palermo", country: "Italy" },
    { name: "Genoa", country: "Italy" },
    { name: "Bologna", country: "Italy" },
    { name: "Florence", country: "Italy" },
    { name: "Bari", country: "Italy" },
    { name: "Catania", country: "Italy" },
  ],
  Spain: [
    { name: "Madrid", country: "Spain" },
    { name: "Barcelona", country: "Spain" },
    { name: "Valencia", country: "Spain" },
    { name: "Seville", country: "Spain" },
    { name: "Zaragoza", country: "Spain" },
    { name: "Málaga", country: "Spain" },
    { name: "Murcia", country: "Spain" },
    { name: "Palma", country: "Spain" },
    { name: "Las Palmas", country: "Spain" },
    { name: "Bilbao", country: "Spain" },
  ],
  Mexico: [
    { name: "Mexico City", country: "Mexico" },
    { name: "Guadalajara", country: "Mexico" },
    { name: "Monterrey", country: "Mexico" },
    { name: "Puebla", country: "Mexico" },
    { name: "Tijuana", country: "Mexico" },
    { name: "León", country: "Mexico" },
    { name: "Juárez", country: "Mexico" },
    { name: "Torreón", country: "Mexico" },
    { name: "Querétaro", country: "Mexico" },
    { name: "San Luis Potosí", country: "Mexico" },
  ],
  Egypt: [
    { name: "Cairo", country: "Egypt" },
    { name: "Alexandria", country: "Egypt" },
    { name: "Giza", country: "Egypt" },
    { name: "Shubra El Kheima", country: "Egypt" },
    { name: "Port Said", country: "Egypt" },
    { name: "Suez", country: "Egypt" },
    { name: "Luxor", country: "Egypt" },
    { name: "Aswan", country: "Egypt" },
    { name: "Asyut", country: "Egypt" },
    { name: "Ismailia", country: "Egypt" },
  ],
};

// Helper function to get cities for a country
export const getCitiesForCountry = (countryName: string): City[] => {
  return CITIES_BY_COUNTRY[countryName] || [];
};

// Get all available countries that have cities
export const getCountriesWithCities = (): string[] => {
  return Object.keys(CITIES_BY_COUNTRY);
};

// Get total number of cities
export const getTotalCitiesCount = (): number => {
  return Object.values(CITIES_BY_COUNTRY).reduce(
    (total, cities) => total + cities.length,
    0
  );
};
